name: News Scraper Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run news scraper
        run: |
          python news_scraper.py

      - name: Upload scraped news artifacts
        uses: actions/upload-artifact@v4
        with:
          name: news-articles-${{ github.run_id }}
          path: |
            news_articles.json
            news_articles.csv

